//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPostales
    {
        public CPostales()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Empresa = new HashSet<Empresa>();
            this.Proveedores = new HashSet<Proveedores>();
            this.Vendedores = new HashSet<Vendedores>();
        }
    
        public short CodigoPostal { get; set; }
        public byte SubCodigoPostal { get; set; }
        public string Localidad { get; set; }
        public byte IdProvincia { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        public virtual ICollection<Vendedores> Vendedores { get; set; }
    }
}
