//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SgPymeDelLagoEntities : DbContext
    {
        public SgPymeDelLagoEntities()
            : base("name=SgPymeDelLagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AjustesStock> AjustesStock { get; set; }
        public DbSet<ArchivosGenerados> ArchivosGenerados { get; set; }
        public DbSet<Articulos> Articulos { get; set; }
        public DbSet<AsientosContables> AsientosContables { get; set; }
        public DbSet<AutenticacionesWSAA> AutenticacionesWSAA { get; set; }
        public DbSet<Bancos> Bancos { get; set; }
        public DbSet<Cajas> Cajas { get; set; }
        public DbSet<CajasAperturas> CajasAperturas { get; set; }
        public DbSet<CajasAperturasDetalle> CajasAperturasDetalle { get; set; }
        public DbSet<CajasMovimientos> CajasMovimientos { get; set; }
        public DbSet<CajasMovimientosDetalle> CajasMovimientosDetalle { get; set; }
        public DbSet<CancelacionFacturas> CancelacionFacturas { get; set; }
        public DbSet<CancelacionFacturasCompra> CancelacionFacturasCompra { get; set; }
        public DbSet<Cheques> Cheques { get; set; }
        public DbSet<CierresIvaCompras> CierresIvaCompras { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<CondicionesPago> CondicionesPago { get; set; }
        public DbSet<ControladoresFiscales> ControladoresFiscales { get; set; }
        public DbSet<CPostales> CPostales { get; set; }
        public DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public DbSet<CuentasContables> CuentasContables { get; set; }
        public DbSet<DatosImpositivos> DatosImpositivos { get; set; }
        public DbSet<Depositos> Depositos { get; set; }
        public DbSet<DiaGeneracionInteres> DiaGeneracionInteres { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<EmpTarjetas> EmpTarjetas { get; set; }
        public DbSet<Errores> Errores { get; set; }
        public DbSet<EstadosCaja> EstadosCaja { get; set; }
        public DbSet<FacturasCompra> FacturasCompra { get; set; }
        public DbSet<FacturasCompraDetalle> FacturasCompraDetalle { get; set; }
        public DbSet<FacturasElectronicas> FacturasElectronicas { get; set; }
        public DbSet<FacturasVenta> FacturasVenta { get; set; }
        public DbSet<FacturasVentaDetalle> FacturasVentaDetalle { get; set; }
        public DbSet<FormasPago> FormasPago { get; set; }
        public DbSet<GeneracionInteres> GeneracionInteres { get; set; }
        public DbSet<Liquidaciones> Liquidaciones { get; set; }
        public DbSet<LiquidacionesFacturas> LiquidacionesFacturas { get; set; }
        public DbSet<Modulos> Modulos { get; set; }
        public DbSet<MovimientosBancos> MovimientosBancos { get; set; }
        public DbSet<MovimientosDepositos> MovimientosDepositos { get; set; }
        public DbSet<ObservacionesCliente> ObservacionesCliente { get; set; }
        public DbSet<OrdenesPedidoFacturas> OrdenesPedidoFacturas { get; set; }
        public DbSet<OrdenesPedidos> OrdenesPedidos { get; set; }
        public DbSet<OrdenesPedidosDetalle> OrdenesPedidosDetalle { get; set; }
        public DbSet<Pagos> Pagos { get; set; }
        public DbSet<PagosDetalle> PagosDetalle { get; set; }
        public DbSet<PeriodosContables> PeriodosContables { get; set; }
        public DbSet<PreciosVenta> PreciosVenta { get; set; }
        public DbSet<Presupuestos> Presupuestos { get; set; }
        public DbSet<PresupuestosDetalles> PresupuestosDetalles { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<Provincias> Provincias { get; set; }
        public DbSet<Recibos> Recibos { get; set; }
        public DbSet<RecibosDetalle> RecibosDetalle { get; set; }
        public DbSet<RecibosInmobiliaria> RecibosInmobiliaria { get; set; }
        public DbSet<ReferentesProveedores> ReferentesProveedores { get; set; }
        public DbSet<RegimenesImpositivos> RegimenesImpositivos { get; set; }
        public DbSet<Remitos> Remitos { get; set; }
        public DbSet<RemitosCompra> RemitosCompra { get; set; }
        public DbSet<RemitosDetalle> RemitosDetalle { get; set; }
        public DbSet<RemitosDetalleCompra> RemitosDetalleCompra { get; set; }
        public DbSet<RemitosXfacturados> RemitosXfacturados { get; set; }
        public DbSet<RetencionesGcia> RetencionesGcia { get; set; }
        public DbSet<Rubros> Rubros { get; set; }
        public DbSet<Seteos> Seteos { get; set; }
        public DbSet<SubRubros> SubRubros { get; set; }
        public DbSet<TiposCF> TiposCF { get; set; }
        public DbSet<TiposCheques> TiposCheques { get; set; }
        public DbSet<TiposConceptoFactura> TiposConceptoFactura { get; set; }
        public DbSet<TiposDocFact> TiposDocFact { get; set; }
        public DbSet<TiposDocumento> TiposDocumento { get; set; }
        public DbSet<TiposFactura> TiposFactura { get; set; }
        public DbSet<TiposImpuestos> TiposImpuestos { get; set; }
        public DbSet<TiposIva> TiposIva { get; set; }
        public DbSet<TiposMovimientosBanco> TiposMovimientosBanco { get; set; }
        public DbSet<TiposMovimientosCaja> TiposMovimientosCaja { get; set; }
        public DbSet<TiposMovimientosDepositos> TiposMovimientosDepositos { get; set; }
        public DbSet<TiposPagos> TiposPagos { get; set; }
        public DbSet<TiposPersona> TiposPersona { get; set; }
        public DbSet<TiposRetenciones> TiposRetenciones { get; set; }
        public DbSet<TiposUsuarios> TiposUsuarios { get; set; }
        public DbSet<TiposVendedores> TiposVendedores { get; set; }
        public DbSet<TiposVendedoresExternos> TiposVendedoresExternos { get; set; }
        public DbSet<UnidadesMedida> UnidadesMedida { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Vendedores> Vendedores { get; set; }
        public DbSet<VendedoresFacturasVenta> VendedoresFacturasVenta { get; set; }
        public DbSet<VendedoresRemitos> VendedoresRemitos { get; set; }
    }
}
