//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaGeneracionInteres
    {
        public DiaGeneracionInteres()
        {
            this.GeneracionInteres = new HashSet<GeneracionInteres>();
        }
    
        public int IdDiaGeneracion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<GeneracionInteres> GeneracionInteres { get; set; }
    }
}
