//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosBancos
    {
        public MovimientosBancos()
        {
            this.CancelacionFacturasCompra = new HashSet<CancelacionFacturasCompra>();
        }
    
        public long IdMovBanco { get; set; }
        public short IdTipoMovBanco { get; set; }
        public short IdTipoPersona { get; set; }
        public int IdPersona { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaEfectivizacion { get; set; }
        public string NroComprobante { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdCheque { get; set; }
    
        public virtual ICollection<CancelacionFacturasCompra> CancelacionFacturasCompra { get; set; }
        public virtual TiposMovimientosBanco TiposMovimientosBanco { get; set; }
        public virtual TiposPersona TiposPersona { get; set; }
    }
}
