//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public Pagos()
        {
            this.PagosDetalle = new HashSet<PagosDetalle>();
        }
    
        public int IdPago { get; set; }
        public short IdTipoDocumento { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int NroProveedor { get; set; }
        public decimal MontoTotal { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public short IdEmpresa { get; set; }
        public string UsrAcceso { get; set; }
        public System.DateTime FechaAcceso { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual TiposDocFact TiposDocFact { get; set; }
        public virtual ICollection<PagosDetalle> PagosDetalle { get; set; }
    }
}
