//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodosContables
    {
        public PeriodosContables()
        {
            this.AsientosContables = new HashSet<AsientosContables>();
        }
    
        public int Periodo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
    
        public virtual ICollection<AsientosContables> AsientosContables { get; set; }
    }
}
