//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincias
    {
        public Provincias()
        {
            this.CPostales = new HashSet<CPostales>();
            this.DatosImpositivos = new HashSet<DatosImpositivos>();
        }
    
        public byte IdProvincia { get; set; }
        public string Provincia { get; set; }
    
        public virtual ICollection<CPostales> CPostales { get; set; }
        public virtual ICollection<DatosImpositivos> DatosImpositivos { get; set; }
    }
}
