//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosInmobiliaria
    {
        public int IdReciboInmobiliaria { get; set; }
        public int IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Ubicacion { get; set; }
        public string Mes { get; set; }
        public decimal Importe { get; set; }
        public decimal Recargo { get; set; }
        public decimal TasaMunicipal { get; set; }
        public decimal CoopAgua { get; set; }
        public decimal EmpresaEnergia { get; set; }
        public decimal CoopGas { get; set; }
        public decimal Otros { get; set; }
        public int IdRegimenImpositivo { get; set; }
        public decimal Total { get; set; }
        public int NumeroRecibo { get; set; }
        public Nullable<decimal> ImpuestoInmobiliaria { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
    }
}
