//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposConceptoFactura
    {
        public TiposConceptoFactura()
        {
            this.FacturasVenta = new HashSet<FacturasVenta>();
            this.FacturasVenta1 = new HashSet<FacturasVenta>();
        }
    
        public int IdConceptoFactura { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<FacturasVenta> FacturasVenta { get; set; }
        public virtual ICollection<FacturasVenta> FacturasVenta1 { get; set; }
    }
}
