//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposIva
    {
        public TiposIva()
        {
            this.FacturasCompraDetalle = new HashSet<FacturasCompraDetalle>();
            this.FacturasVentaDetalle = new HashSet<FacturasVentaDetalle>();
        }
    
        public byte IdTipoIva { get; set; }
        public float PorcentajeIVA { get; set; }
    
        public virtual ICollection<FacturasCompraDetalle> FacturasCompraDetalle { get; set; }
        public virtual ICollection<FacturasVentaDetalle> FacturasVentaDetalle { get; set; }
    }
}
