//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDocFact
    {
        public TiposDocFact()
        {
            this.FacturasCompra = new HashSet<FacturasCompra>();
            this.FacturasVenta = new HashSet<FacturasVenta>();
            this.Pagos = new HashSet<Pagos>();
            this.Recibos = new HashSet<Recibos>();
        }
    
        public short IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<FacturasCompra> FacturasCompra { get; set; }
        public virtual ICollection<FacturasVenta> FacturasVenta { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<Recibos> Recibos { get; set; }
    }
}
