//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public short IdUser { get; set; }
        public string NombreUser { get; set; }
        public short IdTipoUser { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public byte[] PassUser { get; set; }
        public Nullable<System.DateTime> FechaDeBloqueo { get; set; }
        public Nullable<int> NumeroDeIntentos { get; set; }
    
        public virtual TiposUsuarios TiposUsuarios { get; set; }
    }
}
